### ISSUE TITLE
Blog Topic: How to make a pull request with your new post

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-blog#27]
## What is the idea of your topic?

A guide on how to raise a pull request and how to write up your blog post for the DDD East Midlands website. 

This could include snippets, markdown cheatsheets and guidance on how to raise a PR

## Why do you think this would be a good topic for the DDD East Midlands Blog?

We want to encourage others to contribute, and this will help lower the barrier to entry. We can link to this post on the readme and contribution guidelines as well

**Comment by AverageMarcus** [comment]
I'm going to take a stab at this one :)
