### ISSUE TITLE
Blog Topic:  The Northampton Tech Community

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-blog#5]
## What is the idea of your topic?

We have heard from Lincoln about [Why The Community Matters](https://blog.dddeastmidlands.com/2019/08/07/digital-lincoln-post.html) and their local tech scene. We would love to hear from someone in Northampton about their tech community and what makes it excellent - meetups, businesses, hacks and more.

## Why do you think this would be a good topic for the DDD East Midlands Blog?

DDD East Midlands is celebrating all of the East Midlands tech scene and we would love to hear from more of the major cities in the East Mids.

**Comment by nagavenkatakiran** [comment]
Hi Jessica,
I would like to contribute here

**Comment by wordshaker** [comment]
Hey @nagavenkatakiran - I would like these posts to be from a variety of authors who are actively involved in these communities.

Where would you be best placed?
