### ISSUE TITLE
Feature Request: Fix Spelling Mistakes

### ISSUE THREAD

**Issue by wordshaker** [DDDEastMidlandsLimited/dddem-blog#8]
### Describe the feature

There are spelling mistakes scattered in these blogs. Please find them and fix them.

### Advantages

* Makes us look a bit more professional

#### Acceptance Criteria

- [x] Why Community Matters by Digital Lincoln
- [x] Recappin’ DDD East Midlands Speakers’ Workshop
- [x] A Conference For Everyone
- [x] Mentor - Gosia Borzęcka
- [x] Mentor - Matt Brunt
- [x] How To Talk Part 6 - Considering Flow
- [x] How To Talk Part 5 - Planning Structure
- [x] How To Talk Part 4 - Building Confidence
- [x] How To Talk Part 3 - Sparkling Biographies
- [x] Using Sessionize To Submit
- [x] How To Talk Part 2 - Writing a good talk proposal
- [x] How To Talk Part 1 - Coming up with a talk
- [x] DDD East Midlands — Camaraderie, Inclusivity, Support and Tech

**Comment by UltimaBGD** [comment]
I took a look at the "Writing a talk proposal post" and changed a few things I noticed. I'll link a pull request shortly so you can check it out.

**Comment by karentobo** [comment]
I'll take on "Why Community Matters" by Digital Lincoln

**Comment by wordshaker** [comment]
Thank you all for your efforts!
